### PR TITLE
Adding DECaLS and Illustris icons

### PR DESCRIPTION
**Pull request by willettk**
Icons for new surveys from @heathv.

Trying this with a fresh fork to avoid rebase hell.

### CODE REVIEW

**Comment by chrissnyder** [comment]
:+1: 

@murraycu These are going to be part of a couple new, much larger, survey groups that we'll be integrating shortly.

**Comment by murraycu** [comment]
@chrissnyder Thanks. That's the surveys being added in this branch, right?
https://github.com/zooniverse/Galaxy-Zoo/commits/decals_illustris

When it's ready to go live it would be nice to have a couple of days warning, please so I can update the Android app. Hopefully that will not be before August 12th as I'm on vacation until then.

Most importantly, could you _please_ not disable the old surveys before I have updated the Android app. The last 2 times that you changed the surveys, you stopped the old surveys from serving subjects and that broke the app.

**Comment by chrissnyder** [comment]
That all sounds good to me. We aren't looking to launch in the next couple days either, so that timeframe is also probably OK.

These surveys collectively have a lot more data in them than the last set, so it should be the last time we need to do this for awhile.

**Comment by willettk** [comment]
Hi @murraycu - we are just on the verge of launching the new datasets, and
the relevant code should now be in the decals_illustris branch on this
repo. Can you start looking at what this will mean for the app, and if
there's anything we should take into account before throwing the switch?

**Comment by murraycu** [comment]
@willettk As far as I can tell, the branch isn't ready to merge with master, so you can't quite be ready to launch it live. For instance, surely you need a change such as this to actually use the new surveys:
Surely you need a change such as this to actually use the new surveys? :
https://github.com/zooniverse/Galaxy-Zoo/commit/0c445435b391c4b690e972f98abd52f5aa5fb194
(You'd use a version of the commented-out code.)

And there are no survey IDs for decals or illustris so the UI cannot actually request subjects for those surveys. Do you have extra local changes that that you are using for testing, or is this not the correct branch?
https://github.com/zooniverse/Galaxy-Zoo/tree/decals_illustris

I really need to be able to run the (branch of the) regular web UI locally before I can update the Android app.

**Comment by willettk** [comment]
@murraycu Right - there are a couple final steps that I don't know how to do, including generating the survey IDs. I did fix it so that it will call the correct subjects - thanks. 98c3c7259e05d39846075a59f388462a5ce9e031

@chrissnyder - can we activate the subjects and run a test version of the new branch? I think I've committed everything that I can at this point (although I certainly might have missed something).

**Pull request merged**
