### PR TITLE
Adding DECaLS and Illustris counters to profile page. Closes #230.

### LINKED ISSUE #230: New image sets are not populating the counter
Got a report from a user that the counter on his profile page is not updating, and I'm getting the same thing. As you can see, I've done more than 10 classification, but the counter is stuck.

screen shot 2015-09-28 at 11 55 09 am

I think that the new image sets are not populating that counter.

### PR DESCRIPTION
**Pull request by willettk**
I think this adds counters for both sets, but it'd be best if @parrish or @chrissnyder glanced at it first.

### CODE REVIEW

**Comment by chrissnyder** [comment]
Looks alright to me.

**Comment by willettk** [comment]
I fixed a thing!

**Comment by willettk** [comment]
Thanks, @chrissnyder and @edpaget. Have they been deployed yet? I still don't see the new counts on the live page.

**Comment by chrissnyder** [comment]
I haven't yet, waiting on an answer to https://github.com/zooniverse/Galaxy-Zoo/pull/229

**Comment by chrissnyder** [comment]
Deployed.

**Pull request merged**
