### PR TITLE
Add Docker config for development

### PR DESCRIPTION
**Pull request by eatyourgreens**

### CODE REVIEW

**Comment by eatyourgreens** [comment]
@astopy does this look ok to you? It fails for me (Docker on OSX El Cap) at the `npm install` step with an ssh host verification error for github.com.

**Comment by astopy** [comment]
@eatyourgreens Got it! I don't know where the `ssh://` URLs are coming from, but this will force them onto HTTPS instead:

```
RUN git config --global url.https://github.com/.insteadOf ssh://git@github.com/
```

**Comment by eatyourgreens** [comment]
@astopy Thanks! Could  this be the offending dependency? https://github.com/zooniverse/Ubret/blob/galaxy_zoo/package.json#L27

**Comment by astopy** [comment]
Ah, yes that's probably it

**Comment by eatyourgreens** [comment]
Rebased and updated. This is now working for me, running `npm start` in a docker container.

**Comment by astopy** [comment]
I've added an automated docker hub build too: https://hub.docker.com/r/zooniverse/galaxy-zoo/

That way we have a working copy of this even if the dependencies stop being available in the future.

**Pull request merged**
