### PR TITLE
CSS: sloan_singleband: Correct the entries for example images.

### PR DESCRIPTION
**Pull request by murraycu**
This lets people actually see the example images for the
"What are the odd features?" question.

### CODE REVIEW

**Comment by murraycu** [comment]
The examples counts for the "Could this be a disk viewed edge-on?" question are wrong too, but I need someone to confirm that these are the correct example images for the answers *Yes and No" to that question:

Yes:
http://static.zooniverse.org/www.galaxyzoo.org/images/examples/sloan_singleband_1_a-0_0.jpg
http://static.zooniverse.org/www.galaxyzoo.org/images/examples/sloan_singleband_1_a-0_1.jpg

No:
No examples.

**Comment by willettk** [comment]
Confirmed - there should be no edge-on galaxies in the sample, and so both of these examples should be for the "no" category. Rename?

Do we need to change the filename of the static images, or can this be done through the CSS in this commit?

**Comment by murraycu** [comment]
I've fixed that with a couple of simple file renames.

If you could warn me in advance next time, I could check these things via my unit test (for android-galaxyzoo) before you publish them on the website. For instance, please let me know which survey/tree will be live soon, pointing me to a branch or pull request if it's not prepared in git master already.

Or if someone can tell me how to run the tests in the GalaxyZoo website's project, maybe I could add a test via CoffeeScript. Otherwise this will keep happening.

**Comment by willettk** [comment]
We should be able to do that. The next images are in-hand, but not in Galaxy Zoo yet; expected to go live in 2-3 weeks.

**Comment by chrissnyder** [comment]
:+1:

**Pull request merged**
