### PR TITLE
check data type of metadata.mag.abs_r before assuming it is a string

### PR DESCRIPTION
**Pull request by CKrawczyk**
This should close https://github.com/zooniverse/Galaxy-Zoo/issues/255 but since there are no DR2 images on the dev server for GZ I have not checked directly.

### CODE REVIEW

**Comment by willettk** [comment]
@astopy has put some images for DR2 on the dev server now. Could you test this and see if it works, @CKrawczyk? 

I'd like to do it myself, but I'm still having trouble loading the site (see #256), and I'm not sure what I can do about that now.

**Comment by CKrawczyk** [comment]
@astopy or @willettk do you have a GZ ID for a DR2 image I can test?  I want to make sure I am looking at a DR2 image.

**Comment by astopy** [comment]
The ones I put on dev are AGZ000bi3j and AGZ000bi3l.

**Comment by CKrawczyk** [comment]
I can confirm the fix works for my local version for these two subjects:
screen shot 2016-04-12 at 11 06 15 am

screen shot 2016-04-12 at 11 06 26 am

**Comment by willettk** [comment]
Excellent, thanks @CKrawczyk! @astopy - is there anything else we should do to get this (and #253, #258) merged and deployed?

**Comment by astopy** [comment]
This is taking a while to deploy, but it should be up later today.

**Comment by willettk** [comment]
I'll check later. Thanks, Adam!

**Comment by willettk** [comment]
All changes are live and look good. Thanks both @CKrawczyk and @astopy for your help!

**Pull request merged**
