### PR TITLE
Moved skibba to retired list (on his request).

### PR DESCRIPTION
**Pull request by karenlmasters**
Also I'm curious how we set the order of the team list displayed. It's not the order they are in this file... 

Mostly I'd like to move Kyle Willett up the list to hi-light his new title of "Lead Data Scientist".... ;)

### CODE REVIEW

**Comment by willettk** [comment]
Adding content is basically done twice: you add the actual text in the `en.coffee` file, which is set by a variable. Then you tell the website to display that text and in what place in a file like `app/views/team.eco`.

**Comment by willettk** [comment]
We may make small changes to the text this week, @chrissnyder, so don't bother deploying the changes until we're ready to start running the new subjects.

**Comment by chrissnyder** [comment]
:+1:

**Comment by karenlmasters** [comment]
Kyle - thanks for the explanation. That's clearer now. :)

**Comment by karenlmasters** [comment]
Skibba and Hoyle have completely disappeared (not on the retired or current list). Something went wrong?

**Pull request merged**
