### PR TITLE
Full set of changes for new DECaLS and Illustris images.

### PR DESCRIPTION
**Pull request by willettk**
Hopefully everything's properly done, but would really benefit from a review by @chrissnyder or @parrish once the subjects are in Ouroboros.

### CODE REVIEW

**Comment by murraycu** [comment]
How are you testing this without a server that returns the subjects?

**Comment by willettk** [comment]
We'll run a full test with the server. The subjects should be imported
today or tomorrow, I've been told; I'll forward details as soon as I have
them.

**Comment by murraycu** [comment]
Is this ready for testing now?

**Comment by willettk** [comment]
There's a temporary site set up at http://www.galaxyzoo.org/staging/. There
are some obvious issues that I need to fix for the site (question/answer
text is missing for Illustris subjects, for example), but the subjects are
imported into ouroboros. If there's any tests you can do right now, please
take a look.

- Kyle

**Comment by murraycu** [comment]
I'm testing the decals tree now. It looks generally good, but at least one example image is not available from the staging server:
  https://static.zooniverse.org/www.galaxyzoo.org/staging/images/examples/illustris-1_a-1_3.jpg
I get this error page in my browser:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>F538A6E57CBFB56A</RequestId><HostId>CVfnpQqenykJzxjY12UpBztHf3mKbl5/lrNe7lMjCCIVsldCLbCK8xecB7U3IO43</HostId></Error>
```

That's the 4th "No" example image on the "Could this be a disk viewed edge-on?" question.

I guess it's a problem with the staging server rather than the code in this git branch but it would be nice if someone could investigate.

**Comment by murraycu** [comment]
There is a problem with the Illustris tree. The code assumes that the example images have a .jpg extension, so clicking on an example icon to see the full image will try to view this, for instance:
  https://static.zooniverse.org/www.galaxyzoo.org/staging/images/examples/illustris-0_a-0_3.jpg
but the actual image is a .png file:
  https://static.zooniverse.org/www.galaxyzoo.org/staging/images/examples/illustris-1_a-1_3.png
Notice that all the illustris images are png files rather than .jpg files:
https://github.com/zooniverse/Galaxy-Zoo/tree/decals_illustris/public/images/examples

You could make this configurable per survey, or make the code read the actual filename from the .css file, but it would be simpler just to convert the images to .jpg.

**Comment by murraycu** [comment]
Also, for decals, the example images for the checkboxes in decals-10 have the wrong filenames, using -a instead of -x, so the example images are not visible at all. That's the "Do you see any of these odd features in the image?" question.

**Comment by murraycu** [comment]
Something is odd about the Ilustris tree, though so far it's only affecting my custom Coffescript code that I use to read out an XML tree: https://github.com/zooniverse/Galaxy-Zoo/issues/214#issuecomment-138265796

**Comment by murraycu** [comment]
Thanks. See pull request #218 for another commit that's needed.

Please let me know when this is on http://www.galaxyzoo.org/staging/ so I can run my tests again.

**Comment by willettk** [comment]
Will do. Just waiting for @chrissnyder to put a few of the new subjects on
staging so I can test it as well using localhost.

**Comment by murraycu** [comment]
At least at the moment, the illustris example images don't seem to be deployed to staging. For instance, this is not available:
https://static.zooniverse.org/www.galaxyzoo.org/staging/images/examples/illustris-9_a-0_0.jpg
though it should be:
https://github.com/zooniverse/Galaxy-Zoo/tree/decals_illustris/public/images/examples

**Comment by willettk** [comment]
None of the changes made in the last week have been deployed to staging.

**Comment by chrissnyder** [comment]
I've added some test data to dev server. Will show up locally as well. Also deployed the latest to staging.

**Comment by murraycu** [comment]
For the ilustris tree, In addition the the problem with illustris-6 (see pull request #220), the examples counts are wrong for the illustris-10 question ("How many spiral arms are there?")
https://github.com/zooniverse/Galaxy-Zoo/blob/decals_illustris/app/lib/illustris_tree.coffee#L40
There are no example images for these at all, which seems like a problem that shouldn't just be fixed by correcting the counts to 0.

I also notice that there are no dustlane example images for illustris-6 ("Do you see any of these odd features in the image?"), though illustris_tree.coffee correctly doesn't mention any.

These are the actual images that exist in the branch. There are none for illustris-10:
https://github.com/zooniverse/Galaxy-Zoo/tree/decals_illustris/public/images/examples

And these are the mentions of them in the CSS file:
https://github.com/zooniverse/Galaxy-Zoo/blob/decals_illustris/css/common.styl#L948

**Comment by willettk** [comment]
There are no dust lane example images for Illustris, primarily because I
couldn't find a single example (and don't expect any to turn up; the
resolution of the simulation doesn't produce these). However, most members
of the science team voted to keep the decision tree identical to the GZ2
version; hence we have a question that I'm expecting to yield zero real
answers. Would be very interesting if some turned up, though.

The spiral arms number question should map to illustris-9, not 10
(questions start at zero) - I think they have the correct number of
examples.

**Comment by chrissnyder** [comment]
Note this is NOT deployed yet.

**Comment by murraycu** [comment]
https://github.com/zooniverse/Galaxy-Zoo/pull/222 is still necessary,

**Comment by murraycu** [comment]
I've updated my android-galaxyzoo decals_illustris branch and its tests now all pass, so I am ready to release a new Android Galaxy Zoo app whenever this goes live on the site. Thanks for letting me check it first.

**Comment by chrissnyder** [comment]
Many thanks for your contributions! Very happy to give you the time needed.

**Pull request merged**
