### PR TITLE
Update subject selection

### PR DESCRIPTION
**Pull request by bamford**
Overrides PR #292 (sorry @hughdickinson!)

### CODE REVIEW

**Comment by bamford** [comment]
@murraycu We're switching the subject sets again. Sorry this is happening so frequently at the moment! This should be the last change for a couple of months. Let us know when you're ready at your end.

**Comment by astopy** [comment]
I'm going to go ahead and deploy this now since two of the existing groups have finished. Just noting that we will also need to change the gama09 group to gama12 when it finishes, which might be sooner than a couple of months.

**Comment by murraycu** [comment]
@bamford Thanks for the warning. I have updated android-galaxyzoo:
https://github.com/murraycu/android-galaxyzoo/commits/master
and released the new app on the Google Play Store. I will update ios-galaxyzoo in a few days.

**Comment by murraycu** [comment]
And I have now also updated and released the updated GalaxyZoo iPhone app to use these surveys:
https://github.com/murraycu/ios-galaxyzoo/commits/master

**Pull request merged**
