### PR TITLE
decals: Correct the decals-10 example image names.

### PR DESCRIPTION
**Pull request by murraycu**
x-0 is "None" and has no example images. The first one with
example images is x-1 "Ring", not x-0.

### CODE REVIEW

**Comment by murraycu** [comment]
Note that this just does simple renames, changing decals-10_x-n* to decals-10_x-n+1* . github's diff view makes it look more complicated.

**Comment by willettk** [comment]
Ah - my mistake. Thanks, @murraycu - I've tested both versions of the tree and the order in this PR is correct.

@chrissnyder - can we merge this into master?

**Comment by willettk** [comment]
Many thanks. Can this be deployed to staging?

**Comment by chrissnyder** [comment]
Yep, deploying now.

**Pull request merged**
