### PR TITLE
Add GAMA-KiDS dataset

### PR DESCRIPTION
**Pull request by bamford**
This PR should include (almost) all the changes required to include the GAMA-KiDS datasets in Galaxy Zoo.

I believe the remaining todos are:
- [x] We need an icon at public/images/gz-icon-gama.png (I think one already exists somewhere)
- [x] Copy images from s3://gzgama/gamazoo{09,12,15} to a standard zooniverse S3 location
- [x] Ingest manifests (GAMA regions 09, 12,15 as separate groups)
- [x] Add group id and workflowId for each GAMA region to app/lib/config.coffee
- [x] Draft blog post at https://wordpress.com/post/blog.galaxyzoo.org/8767
- [ ] A good check that everything is working!

The manifests can be obtained from:
http://gzgama.s3.amazonaws.com/manifests/gama09_manifest.json
http://gzgama.s3.amazonaws.com/manifests/gama12_manifest.json
http://gzgama.s3.amazonaws.com/manifests/gama15_manifest.json

### CODE REVIEW

**Comment by bamford** [comment]
For the record, my log for this work is below:

> Forked zooniverse/Galaxy-Zoo to bamford/Galaxy-Zoo and created branch gama from master.
> 
> Some instructions at:
> https://github.com/zooniverse/Galaxy-Zoo/wiki/How-to-add-a-new-set-of-images-to-Galaxy-Zoo
> 
> Example code used for the latest decals data upload is in this repo: https://github.com/willettk/decals/tree/dr2_threaded/python
> 
> Final data from Lee is at:
> http://www.astro.ljmu.ac.uk/~lsk/galaxyzoo/
> 
> Some relevant scripts stored at
> https://github.com/bamford/gzgama/tree/preparation/
> 
> Copied app/lib/decals_tree.coffee to gama_tree.coffee and edited:
> * changed Decals —> GAMA
> * modified first question to remove mention of disks
> 
> Added gama questions and answers to app/lib/en.coffee
> Also added additional GAMA KiDS text to labels for other pages, including paragraphs for the “relaunched” and “story”.  Minimally updated home.call_to_action.
> 
> Added gama text to:
> * app/views/astronomers.eco
> * app/views/profile.eco
> * app/views/story.eco
> 
> Added gama09, gama12, gama15 entries in app/lib/config.coffee, but need to add correct hashes.
> Separated like this so we can turn each dataset on separately.
> 
> For remaining files with ‘decals’ in, ‘gama’ lines copied and edited:
> * app/models/subject.coffee
>     * set to show GAMA-KiDs G09 region 25% of time (DECaLS DR2, SDSS missing and FERENGI_2 rest)
> * css/common.styl
> * css/profile.styl
> 
> All examples copied to public/images/examples/gama
> Lee had numbered tasks according to Coleman’s question tree diagrams, but tasks here are numbered differently. Checkmark answers also need to be labelled 'x', not ‘a'.
> Wrote public/images/examples/gama/gama_rename.sh to copy files to public/images/examples folder and name appropriately.
> Added corresponding entries to css/common.styl
> (Wrote public/images/examples/gama/gama_check to check all example files present.)
> 
> All images uploaded to s3://gzgama/
> This is a bucket in Steven’s zooniverse funded AWS account.
> Maybe best to copy these to a standard location (and modify manifests accordingly).
> 
> Wrote make_gama_metadata.py, adapted from make_decals_metadata_dr2.py, to convert metadata provided by Lee into format ready for ingesting into Ouroboros.
> Manifests uploaded to s3://gzgama/manifests:
> http://gzgama.s3.amazonaws.com/manifests/gama{09,12,15}_metadata.{csv,fits}
> 
> Rebased gama branch on latest zooniverse/Galaxy-Zoo/master - only conflict was in subject.coffee as FERENGI_2 dataset has been enabled (modified info above).
>

**Comment by bamford** [comment]
Perhaps PRs #267 and #263 should be merged first.

**Comment by bamford** [comment]
Images being uploaded to s3://zooniverse-data/project_data/galaxy_zoo/gama{09,12,15}
Manifests converted to json (links in top post modified).

**Comment by bamford** [comment]
Formatting of the JSON manifests was wrong.  Fixed in [bamford/gzgama:c0a71af2d](https://github.com/bamford/gzgama/commit/c0a71af2d28437956fa9932b5dacf70ac94eb59b) and manifests replaced at above urls.

**Comment by astopy** [comment]
@bamford The subjects have been ingested into Ouroboros now. Here are the group and workflow IDs:

* GAMA09
  * Group: 5853fa7b95ad361930000001
  * Workflow: 5857c2bb95ad365e69000690
* GAMA12
  * Group: 5853faaf95ad361930000002
  * Workflow: 5857df7c95ad364bc30009a3
* GAMA15
  * Group: 5853fab395ad361930000003
  * Workflow: 58580c8295ad362a4a0001fa

**Comment by astopy** [comment]
Note that the subjects are still marked as inactive. If we're ready to activate them then I can, but with there being three groups already active I'm not sure if we want to wait. (At least until the ferengi data is done?)

**Comment by bamford** [comment]
I have merged PRs #267 and #263 into this PR, and pulled latest master, so it should apply without a hitch.

**Pull request merged**
