### PR TITLE
Switch to gama12

### PR DESCRIPTION
**Pull request by bamford**
The gama09 dataset is complete.  Time to change to gama12.

Could this be deployed asap?  Thanks!

### CODE REVIEW

**Comment by bamford** [comment]
Notifying @murraycu in case any action required.

**Comment by murraycu** [comment]
I have made the changes to the Android app
https://github.com/murraycu/android-galaxyzoo/commit/68e39a5bf8364b11f39c328a36a6447b12ce8666
and can release a new version as soon as this is live on the main site. Thanks for letting me know.

I'll do the iPhone app soon afterwards.


However, you already seem to have disabled the gama09 survey on the servers:
https://www.galaxyzoo.org/_ouroboros_api/projects/galaxy_zoo/groups/5853fa7b95ad361930000001/subjects?limit=1
(It returns an empty file, with no subjects.)

This breaks existing app installations (luckily not fatally in this case, because there are other surveys for the app to try) and causes the regular web page to silently make failing requests to the server. This is about the 10th time that this has happened. There's a comment in the file asking you not to do this.
https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/models/subject.coffee#L97

The gama12 survey is not active on the servers yet either:
https://www.galaxyzoo.org/_ouroboros_api/projects/galaxy_zoo/groups/5853fa7b95ad361930000002/subjects?limit=1

**Comment by bamford** [comment]
I think the reason you aren't getting any gama09 subjects is that the dataset was completed last week. All the subjects have been automatically.

gama12 is enabled. The id in your query is wrong: https://www.galaxyzoo.org/_ouroboros_api/projects/galaxy_zoo/groups/5853faaf95ad361930000002/subjects?limit=1

Sorry the switchover happened so quickly (again).

**Comment by murraycu** [comment]
> All the subjects have been automatically retired.

If this is really automatic, can that be changed? It would be better to just discard unneeded submissions.

> gama12 is enabled. The id in your query is wrong

Ah, sorry. Yes. Thanks. I stupidly just changed the 1 to a 2 after I manually investigated the gama09 problem.

**Comment by astopy** [comment]
It is automatic, and it's not something we can change. Getting people to do classifications when they're not needed would be a waste of their time, and that's something we avoid.

**Comment by bamford** [comment]
>> All the subjects have been automatically retired.
> If this is really automatic, can that be changed?

Yes, each subject has a retirement limit in its metadata (generally 40) and after that number of classifications has been reached it is no longer shown.

> It would be better to just discard unneeded submissions.

We'd don't want to request lots of classifications we don't need and wouldn't intentionally throw away information!  This procedure is done to ensure that we end up with a fairly uniform distribution of classifications across the subjects.

I doubt there will be any significant changes to Ouroboros now.  Everything currently using that system, including Galaxy Zoo, is due to be ported over to Panoptes project builder system that every new project has used for the past couple of years.  That won't be a fast process though - there should be quite a lot of time for testing.

**Comment by astopy** [comment]
Our preference is usually to have the site display a message explaining that the project is currently out of data, asking the user to come back later or directing them to other, similar projects. (Whether or not GZ specifically does that correctly, I don't know.)

Either way, as @bamford said, there isn't any development time to do anything beyond essential maintenance in Ouroboros so we won't be changing the way that works. In Panoptes, if the project is out of data it shows retired data to the user with a message explaining that the data is finished -- so the user knows their classifications aren't needed, but they can keep going if they want to.

**Comment by murraycu** [comment]
That sounds great. Thanks.

**Pull request merged**
