### PR TITLE
Change out of data message to something more accurate

### PR DESCRIPTION
**Pull request by adammcmaster**

### CODE REVIEW

**Comment by adammcmaster** [comment]
This is live now

**Comment by murraycu** [comment]
Are there plans for a new set of subjects?

**Comment by adammcmaster** [comment]
@murraycu I think we're finished now with Galaxy Zoo on Ouroboros. The current data set finished a bit quicker than I think we were expecting, but a Panoptes-based version is under construction and it's close enough that it doesn't make sense to add more data to Ouroboros.

**Comment by murraycu** [comment]
Is there some beta version that I can try, so I can try to adapt the GalaxyZoo iPhone and Android apps to the new API before the official public release?

**Comment by adammcmaster** [comment]
The beta project is here: https://www.zooniverse.org/projects/zookeeper/galaxy-zoo

And the API documentation is here: https://panoptes.docs.apiary.io/#

You might also want to check out the general Zooniverse mobile app: https://github.com/zooniverse/mobile

**Pull request merged**
