### PR TITLE
Add missing_manga explore page

### PR DESCRIPTION
**Pull request by astopy**
I've thrown together and deployed this basic version so that it's not broken anymore. Feedback welcome on what else to include.

### CODE REVIEW

**Comment by astopy** [comment]
Example here: https://www.galaxyzoo.org/#/examine/AGZ000emhu

**Comment by astopy** [comment]
Note that any new text will need translations. (I don't know how the translations work at all, so help appreciated with that.)

**Comment by CKrawczyk** [comment]
Can you add in the `skyserver` link as well:
```
<div class="row">
  <span class="key"></span>
  <span class="value">
    <a target="_blank" href="http://skyserver.sdss.org/dr9/en/tools/explore/obj.asp?ra=<%= @subject.coords[0] %>&dec=<%= @subject.coords[1] %>"><%- I18n.t 'examine.skyserver_link' %></a>
  </span>
</div>
```

It should look similar to the sdss_lost_set page: https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/views/examine/sdss_lost_set.eco

**Comment by astopy** [comment]
@CKrawczyk Thanks. I've added that and copies a couple of other bits from the sdss_lost_set and sloan pages.

**Pull request merged**
