### PR TITLE
Adding German translation

### PR DESCRIPTION
**Pull request by willettk**

### CODE REVIEW

**Comment by murraycu** [comment]
Surely this should only be done when the German translation is ready? It doesn't seem to be complete in translations.zooniverse.org.

**Comment by willettk** [comment]
Not 100%, but the decision tree, science questions, and front page material
are all in German. I'm fine putting out a partial translation - I'd much
rather have classifiers be able to participate than hold it up because we
haven't translated the biographies of the entire science team.

**Comment by murraycu** [comment]
If you have some contact with the German translations, you might want to ask if they really mean to use "Smooth" in the German translations. It looks very odd to me and probably looks awful to German speakers. "glatt" (smooth) or "eben" (even) might be appropriate, though the English is rather ambiguous.

For instance, from
http://translations.zooniverse.org/#/projects/galaxy_zoo :

questions.decals-0.answers.a-0 : "Smooth"

questions.decals-0.text: "Ist die Galaxie smooth und gleichmäßig, ohne Anzeichen einer Scheibe?"

**Comment by willettk** [comment]
I have votes from two astronomers/native German speakers for **gleichmäßig**.

**Comment by murraycu** [comment]
Possibly, but that's already being used for "round" in
"Ist die Galaxie smooth und gleichmäßig, ohne Anzeichen einer Scheibe?"
as a translation of
"Is the galaxy simply smooth and rounded, with no sign of a disk?"

**Comment by willettk** [comment]
What about:

"Ist die Galaxie gleichmäßig und rundlich, ohne Anzeichen einer Scheibe?"

**Comment by murraycu** [comment]
Maybe, but I'm neither a native German speaker nor an Astronomer, so it shouldn't be me who approves it.

**Comment by willettk** [comment]
Right. Have asked again.

**Comment by willettk** [comment]
I deployed translations for:

*"Ist die Galaxie gleichmäßig und annähernd rund, ohne Anzeichen einer Scheibe?"*

Think I've removed "smooth" from all the German text.

**Comment by murraycu** [comment]
Thanks. But that corrected translation doesn't seem to be used on the website yet.

**Comment by murraycu** [comment]
I've just pressed the "Deploy" button. That then says we can view it here:
http://www.galaxyzoo.org/?lang=bc1954d796172b17#/classify
which has the correct text, though the normal site, does not:
http://www.galaxyzoo.org/?lang=de#/classify

**Comment by willettk** [comment]
I believe deploying any translation changes to the live site still requires
manual intervention, despite the "Deploy" button on the site.
https://github.com/zooniverse/Galaxy-Zoo#what-do-i-do-when-i-add-new-text-to-the-site

I don't have the developer credentials to do that, so we'll have to track
down and ask someone who does. Before that's done, are there any other
existing issues you see with the German translations anywhere in GZ?

**Comment by murraycu** [comment]
Thanks.

The 
  "Note: Please always classify the galaxy in the center of the image."
text was not translated. I have translated that as
  "Bitte klassifiziere immer die Galaxie in der Bildmitte".
  (using the informal du instead of formal Sie, as in the other translated text.)
I didn't find a good equivalent for the (superfluous) "Note: " part, so someone might want to check that. 

Otherwise, it seems complete enough.

**Comment by willettk** [comment]
Hi @eatyourgreens - we've saved the latest translations for German Galaxy Zoo on the Translations site. Could you deploy them re: https://github.com/zooniverse/Galaxy-Zoo/blob/master/README.md#what-do-i-do-when-i-add-new-text-to-the-site ?

**Comment by eatyourgreens** [comment]
Hi @willettk , I've just pressed the deploy button. Are the translations showing up now?

**Comment by willettk** [comment]
Yep - thanks, @eatyourgreens. New text seems to show up fine. Closes #239.

**Pull request merged**
