### PR TITLE
decals: Correct decals_10* example filename to decals-*.

### PR DESCRIPTION
**Pull request by murraycu**
To match the names mentioned in css/common.styl and to match
the expected filenames generated by the code.

### CODE REVIEW

**Comment by willettk** [comment]
Already addressed with d41ea93fd6a17706ef7ce234aae83397665c5f39.

**Comment by murraycu** [comment]
Commit https://github.com/zooniverse/Galaxy-Zoo/commit/d41ea93fd6a17706ef7ce234aae83397665c5f39 is in a different branch (decals_illustris_fixes), not decals_illustris.

**Comment by willettk** [comment]
Yes - I'm amassing fixes in there and then will merge back into
decals_illustris. I've merged your commits into that branch.

**Comment by murraycu** [comment]
OK. That does make it hard for me to know which branch to work with. It should be easier for you to just just use the one branch.

**Comment by willettk** [comment]
Fair enough - I can merge changes back into decals_illustris and work there
from now on. Any changes in the last week aren't deployed to staging yet,
though (I don't have the authority to do that).

**Comment by murraycu** [comment]
Thanks.

**Comment by willettk** [comment]
All changes will be in https://github.com/zooniverse/Galaxy-Zoo/tree/decals_illustris from now on (I've included renaming the checkbox files for both samples). Hopefully they'll be deployed soon so we can test them.

**Pull request closed without merging**
